# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  cmd-dev-strapi:
    desc: Forward command to be executed in dev/strapi
    dir: dev/strapi
    cmds:
      - "{{.CLI_ARGS}}"

  cmd-dev-plugin:
    desc: Forward command to be executed in dev/plugin
    dir: plugin
    cmds:
      - "{{.CLI_ARGS}}"

  start-plugin-watch:
    internal: true
    desc: Start plugin watch mode
    cmds:
      - task cmd-dev-plugin -- npm run watch:link

  start-strapi-dev:
    desc: Start Strapi development environment
    cmds:
      - task cmd-dev-strapi -- npm run dev

  start-local-dev:
    desc: Start local development environment
    deps:
      - start-plugin-watch
      - start-strapi-dev

  test-install-published-package:
    desc: Test installation of the package locally
    cmds:
      - |
        set -e
        mkdir -p .tmp
        cd .tmp
        npm pack ../plugin
        npx create-strapi@latest test-strapi --quickstart --no-run
        PLUGIN_TARBALL=$(ls strapi-plugin-json-schema-validation-*.tgz | head -n 1)
        cd test-strapi
        npm install "../$PLUGIN_TARBALL"
  test-cleanup:
    desc: Clean up test artifacts
    dir: .
    cmds:
      - rm -rf .tmp
