name: 🚀 Release Please - strapi-plugin-json-schema-validation

on:
  pull_request:
    # Trigger only when a PR is merged (i.e., closed and merged)
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_job:
    name: 🏷️ Semantic Release & Tagging
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugin
    outputs:
      plugin--release_created: ${{ steps.release_please.outputs.release_created }}
      plugin--tag_name: ${{ steps.release_please.outputs.tag_name }}

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v6
        with:
          # Fetch all history to accurately calculate semantic version
          fetch-depth: 0

      - name: ⚙️ Semantic Release (Tagging Only)
        id: release_please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
          config-file: .github/release-please-config-main.json
          manifest-file: .github/.release-please-manifest-main.json

  publish-to-npm:
    name: 📦 Publish package to npm
    needs: release_job
    # We have path output in config file https://github.com/googleapis/release-please-action#path-outputs
    if: needs.release_job.outputs['plugin--release_created']
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugin
    permissions:
      contents: read
      id-token: write

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v6

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false # never use caching in release builds

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm run test:ts:front && npm run test:ts:back

      - name: 🏗️ Build package
        run: npm run build --if-present

      - name: ✅ Verify package
        run: npm run verify

      - name: 📦 Publish package
        run: npm publish
